language: cpp
compiler:
  - gcc

env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU
    - BUILD_TYPE="RELEASE"
    # CMAKE
    - CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz"
    - CMAKE_ROOT=${HOME}/cmake
    - CMAKE_SOURCE=${CMAKE_ROOT}/source
    - CMAKE_INSTALL=${CMAKE_ROOT}/install

before_install:
 # CMAKE most recent version
 - >
    if [ "$(ls -A ${CMAKE_INSTALL})" ]; then
      echo "CMake found in cache.";
      ls -A ${CMAKE_INSTALL}
      export PATH=${CMAKE_INSTALL}/bin:${PATH};
      cmake --version
    else
      mkdir --parent ${CMAKE_SOURCE}
      mkdir --parent ${CMAKE_INSTALL}
      ls -A ${CMAKE_INSTALL}
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${CMAKE_INSTALL}
      export PATH=${CMAKE_INSTALL}/bin:${PATH};
      cmake --version
    fi

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-filesystem-dev 
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install
  - export COMMONDIR=`pwd`/install/lib/cmake/;

script:
  - make install -j${NUM_CPU}
  # test building exe from installed
  # build exampleLibFoo
  - cd ${TRAVIS_BUILD_DIR}/exampleLibFoo
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DFoo_DIR=${COMMONDIR}/Foo
  - make install -j${NUM_CPU}
  # build exampleLibFooer
  - cd ${TRAVIS_BUILD_DIR}/exampleLibFooer
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DFooer_DIR=${COMMONDIR}/Fooer
  - make install -j${NUM_CPU}
  # build exampleLibBoostFooer
  - cd ${TRAVIS_BUILD_DIR}/exampleLibBoostFooer
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DBoostFooer_DIR=${COMMONDIR}BoostFooer
  - make install -j${NUM_CPU}
  
  # build separately the libs
  # build Foo
  - cd ${TRAVIS_BUILD_DIR}/libFoo
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install
  - make install -j${NUM_CPU}
  - export FOODIR=`pwd`/install/lib/cmake/Foo/;
  # build Fooer
  - cd ${TRAVIS_BUILD_DIR}/libFooer
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DFoo_DIR=${FOODIR}
  - make install -j2
  - export FOOERDIR=`pwd`/install/lib/cmake/Fooer/;
  # build BoostFooer
  - cd ${TRAVIS_BUILD_DIR}/libBoostFooer
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DFooer_DIR=${FOOERDIR}
  - make install -j${NUM_CPU}
  - export BOOSTFOOERDIR=`pwd`/install/lib/cmake/BoostFooer/;
  
  # build separately the exe
  # build exampleLibFoo
  - cd ${TRAVIS_BUILD_DIR}/exampleLibFoo
  - mkdir buildsolo && cd buildsolo
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DFoo_DIR=${FOODIR}
  - make install -j${NUM_CPU}
  # build exampleLibFooer
  - cd ${TRAVIS_BUILD_DIR}/exampleLibFooer
  - mkdir buildsolo && cd buildsolo
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DFooer_DIR=${FOOERDIR}
  - make install -j${NUM_CPU}
  # build exampleLibBoostFooer
  - cd ${TRAVIS_BUILD_DIR}/exampleLibBoostFooer
  - mkdir buildsolo && cd buildsolo
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DBoostFooer_DIR=${BOOSTFOOERDIR}
  - make install -j${NUM_CPU}


cache:
  directories:
    - $CMAKE_INSTALL